---
steps:
  - label: ":debian: Build & Package & Test"
    key: build
    command: ".buildkite/build.sh"
    artifact_paths:
      - "build-jammy/*"

  - label: ":debian: Publish deb"
    depends_on: build
    command:
      - >
        aptly-upload
        --aptly-url https://apt-repo.kx.gd
        --retries 3
        --repo kx-builds-jammy
        --series jammy
        build-jammy/*.deb
    retry:
      automatic: true
    plugins:
      artifacts#v1.2.0:
        download: "build-jammy/*.deb"
      docker#v1.4.0:
        image: "${ECR}/ci-tools"
        always-pull: true
        workdir: /src
        environment:
          - APTLY_UNAME
          - APTLY_PASSWD
